<Project Sdk="Microsoft.NET.Sdk">

  <Import Project="..\..\common.props" />

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <RootNamespace>Educational</RootNamespace>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
        <PackageReference Include="Volo.Abp.Swashbuckle" Version="9.2.0" />
       <PackageReference Include="Volo.Abp.SettingManagement.Application" Version="9.2.0" />
	  <ProjectReference Include="..\Educational.Domain\Educational.Domain.csproj" />
    <ProjectReference Include="..\Educational.Application.Contracts\Educational.Application.Contracts.csproj" />
    <ProjectReference Include="..\Educational.EntityFrameworkCore\Educational.EntityFrameworkCore.csproj" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Core" Version="2.3.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />

    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.4" />
    <PackageReference Include="Yitter.IdGenerator" Version="1.0.14" />
  </ItemGroup>

</Project>
